import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import vm from 'node:vm';
import {applySteamSnapshot} from '../netlify/functions/_lib/steam-builds.mjs';
import {applyAdminGameConfig} from '../netlify/functions/_lib/game-config.mjs';
import {resolveDisplayStatus} from '../netlify/functions/_lib/game-status.mjs';
import {createGameStatusHandler} from '../netlify/functions/game-status.mjs';
const root=new URL('../',import.meta.url);
const read=name=>readFileSync(new URL(name,root),'utf8');
const config=JSON.parse(read('data/game-status.json'));
test('inZOI participates in the shared catalog, listing, SEO and database registration',()=>{
  const game=config.games.inzoi;
  assert.equal(game.appId,'2456740');
  assert.equal(game.supportedVersion,'0.10.4');
  assert.equal(game.verifiedBuildId,'25336085');
  const context=vm.createContext({});
  const script=read('script.js');
  vm.runInContext(script.slice(script.indexOf('const fallbackGameStatuses ='),script.indexOf('const isBuildAwaitingVerification ='))+'\nthis.games=fallbackGameStatuses;',context);
  const {displayStatus,...entry}=game;
  assert.deepEqual(JSON.parse(JSON.stringify(context.games.inzoi)),entry);
  for(const file of ['index.html','preklady.html']) assert.equal([...read(file).matchAll(/data-game-status="inzoi"/g)].length,1);
  assert.match(read('user-system.js'),/inzoi: \{ name: 'inZOI', page: 'inzoi.html', image: 'assets\/inZOI\/Zoi_hl.jpg' \}/);
  const detail=read('inzoi.html');
  assert.match(detail,/<body data-game="inzoi">/);
  assert.match(detail,/data-download data-game="inzoi"/);
  assert.match(detail,/data-comments-list/);
  assert.match(detail, /<title>inZOI čeština – český překlad ke stažení \| Nio Localization<\/title>/);
  assert.match(detail, /<h1>inZOI čeština<\/h1>/);
  assert.match(detail,/rel="canonical" href="https:\/\/nioczloc.com\/inzoi.html"/);
  const schema=JSON.parse(detail.match(/<script type="application\/ld\+json">(.*?)<\/script>/)[1]);
  assert.equal(schema.url,'https://nioczloc.com/inzoi.html');
  for(const file of ['Zoi_hl.jpg',...Array.from({length:5},(_,i)=>`Zoi_${i+1}.png`)]) assert.ok(existsSync(new URL(`assets/inZOI/${file}`,root)));
  assert.equal([...detail.matchAll(/<img src="assets\/inZOI\//g)].length,6);
  const sql=read('SQL EDITOR/SUPABASE-INZOI.sql');
  for(const table of ['comments','bug_reports','game_ratings','download_totals']) assert.match(sql,new RegExp(`alter table public\\.${table}`));
  assert.match(sql,/insert into public\.game_versions/);
  assert.match(sql,/insert into public\.download_totals/);
  assert.doesNotMatch(sql,/create (or replace )?function|create policy|disable row level security/i);
});
test('inZOI refresh never promotes the latest build into the administrator verified value',async()=>{
  const next={schemaVersion:1,lastCheckedAt:new Date().toISOString(),games:{inzoi:{appId:'2456740',currentBuildId:'25336086',lastSteamUpdate:'2026-10-05T06:00:00Z'}}};
  const handler=createGameStatusHandler({loadConfig:async()=>config,openStore:()=>({get:async()=>null,setJSON:async()=>{}}),fetchManualSnapshot:async games=>{assert.deepEqual(Object.keys(games),['inzoi']);return next;}});
  const result=await handler({httpMethod:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gameSlug:'inzoi'})});
  assert.equal(result.statusCode,200);
  const payload=JSON.parse(result.body);
  assert.equal(payload.refresh.fresh,true);
  assert.equal(payload.games.inzoi.verifiedBuildId,'25336085');
  assert.equal(payload.games.inzoi.currentBuildId,'25336086');
  assert.equal(payload.games.inzoi.displayStatus.key,'pending');
  const applied=applySteamSnapshot(config,next);
  for(const slug of Object.keys(config.games).filter(slug=>slug!=='inzoi')) assert.deepEqual(applied.games[slug],config.games[slug]);
  const admin=applyAdminGameConfig(config,[{game_slug:'inzoi',verified_build_id:'25336087',steam_app_id:'2456740'}]);
  assert.equal(applySteamSnapshot(admin,next).games.inzoi.verifiedBuildId,'25336087');
  assert.equal(resolveDisplayStatus({...config.games.inzoi,statusOverride:{status:'broken'}}).key,'broken');
});
